export const musicData = [
    {id: 1, author: 'Madonna', trackName: 'Frozen'},
    {id: 2, author: 'Nirvana', trackName: 'Smells Like Teen Spirits'},
    {id: 3, author: 'The Beatles', trackName: 'Hey, Jude'},
    {id: 4, author: 'The Beach Boys', trackName: 'Good Vibrations'},
    {id: 5, author: 'The Rolling Stones', trackName: 'Satisfaction'},
    {id: 6, author: 'Black', trackName: 'Wonderful Life'},
    {id: 7, author: 'The Cranberries', trackName: 'Zombie'},
    {id: 8, author: 'Chris Rea', trackName: 'The Road To Hell'},
    {id: 9, author: 'Linkin Park', trackName: 'Numb'},
    {id: 10, author: 'Alphaville', trackName: 'Forever Young'},
    {id: 11, author: 'Boris Shafutinsky', trackName: 'third of september'},
    {id: 12, author: 'Metallica', trackName: 'nothing else matter'},
    {id: 13, author: 'Fleetwood Mac', trackName: 'Dreams'},
]
